import {
  CREATE_SOURCE,
  ISegment,
  ISegmentData
} from '@src/entities/segment/segment.types'
import { Segment } from '@src/entities/segment/segment'
import { ID_TYPE } from '@src/entities'

// export const mockSegmentData = (): ISegmentData[] => [
//   {
//     create_source: CREATE_SOURCE.CREATE,
//     department_name: '개인화서비스개발팀',
//     description: '2N_대홍마_디타겟팅용 최근 14일 접속유저',
//     id: 613,
//     include_columns: ['id'],
//     mail: 'dltkr77@netmarble.com',
//     manager_name: '이삭 [Sack Lee]',
//     name: '2N_TWHKMO_DE 14',
//     phone: '02-2271-6514',
//     query_config: { meta: { idType: ID_TYPE.ADID } },
//     restore_content: null,
//     schedules: [],
//     target_games: ['acasino', 'afive'],
//     created_datetime: '2021-07-01T08:24:35.000Z',
//     modified_datetime: '2021-07-01T08:24:55.000Z'
//   },
//   {
//     create_source: CREATE_SOURCE.CREATE,
//     department_name: '개인화서비스개발팀',
//     description: '2N_대홍마_디타겟팅용 최근 14일 접속유저',
//     id: 613,
//     include_columns: ['id'],
//     mail: 'dltkr77@netmarble.com',
//     manager_name: '이삭 [Sack Lee]',
//     name: '2N_TWHKMO_DE 14',
//     phone: '02-2271-6514',
//     query_config: { meta: { idType: ID_TYPE.ADID } },
//     restore_content: null,
//     schedules: [],
//     target_games: ['acasino', 'afive'],
//     created_datetime: '2021-07-01T08:24:35.000Z',
//     modified_datetime: '2021-07-01T08:24:55.000Z'
//   },
//   {
//     create_source: CREATE_SOURCE.CREATE,
//     department_name: '개인화서비스개발팀',
//     description: '2N_대홍마_디타겟팅용 최근 14일 접속유저',
//     id: 613,
//     include_columns: ['id'],
//     mail: 'dltkr77@netmarble.com',
//     manager_name: '이삭 [Sack Lee]',
//     name: '2N_TWHKMO_DE 14',
//     phone: '02-2271-6514',
//     query_config: { meta: { idType: ID_TYPE.ADID } },
//     restore_content: null,
//     schedules: [],
//     target_games: ['acasino', 'afive'],
//     created_datetime: '2021-07-01T08:24:35.000Z',
//     modified_datetime: '2021-07-01T08:24:55.000Z'
//   },
//   {
//     create_source: CREATE_SOURCE.CREATE,
//     department_name: '개인화서비스개발팀',
//     description: '2N_대홍마_디타겟팅용 최근 14일 접속유저',
//     id: 613,
//     include_columns: ['id'],
//     mail: 'dltkr77@netmarble.com',
//     manager_name: '이삭 [Sack Lee]',
//     name: '2N_TWHKMO_DE 14',
//     phone: '02-2271-6514',
//     query_config: { meta: { idType: ID_TYPE.ADID } },
//     restore_content: null,
//     schedules: [],
//     target_games: ['acasino', 'afive'],
//     created_datetime: '2021-07-01T08:24:35.000Z',
//     modified_datetime: '2021-07-01T08:24:55.000Z'
//   },
//   {
//     create_source: CREATE_SOURCE.CREATE,
//     department_name: '개인화서비스개발팀',
//     description: '2N_대홍마_디타겟팅용 최근 14일 접속유저',
//     id: 613,
//     include_columns: ['id'],
//     mail: 'dltkr77@netmarble.com',
//     manager_name: '이삭 [Sack Lee]',
//     name: '2N_TWHKMO_DE 14',
//     phone: '02-2271-6514',
//     query_config: { meta: { idType: ID_TYPE.ADID } },
//     restore_content: null,
//     schedules: [],
//     target_games: ['acasino', 'afive'],
//     created_datetime: '2021-07-01T08:24:35.000Z',
//     modified_datetime: '2021-07-01T08:24:55.000Z'
//   },
//   {
//     create_source: CREATE_SOURCE.CREATE,
//     department_name: '개인화서비스개발팀',
//     description: '2N_대홍마_디타겟팅용 최근 14일 접속유저',
//     id: 613,
//     include_columns: ['id'],
//     mail: 'dltkr77@netmarble.com',
//     manager_name: '이삭 [Sack Lee]',
//     name: '2N_TWHKMO_DE 14',
//     phone: '02-2271-6514',
//     query_config: { meta: { idType: ID_TYPE.ADID } },
//     restore_content: null,
//     schedules: [],
//     target_games: ['acasino', 'afive'],
//     created_datetime: '2021-07-01T08:24:35.000Z',
//     modified_datetime: '2021-07-01T08:24:55.000Z'
//   },
//   {
//     create_source: CREATE_SOURCE.CREATE,
//     department_name: '개인화서비스개발팀',
//     description: '2N_대홍마_디타겟팅용 최근 14일 접속유저',
//     id: 613,
//     include_columns: ['id'],
//     mail: 'dltkr77@netmarble.com',
//     manager_name: '이삭 [Sack Lee]',
//     name: '2N_TWHKMO_DE 14',
//     phone: '02-2271-6514',
//     query_config: { meta: { idType: ID_TYPE.ADID } },
//     restore_content: null,
//     schedules: [],
//     target_games: ['acasino', 'afive'],
//     created_datetime: '2021-07-01T08:24:35.000Z',
//     modified_datetime: '2021-07-01T08:24:55.000Z'
//   },
//   {
//     create_source: CREATE_SOURCE.CREATE,
//     department_name: '개인화서비스개발팀',
//     description: '2N_대홍마_디타겟팅용 최근 14일 접속유저',
//     id: 613,
//     include_columns: ['id'],
//     mail: 'dltkr77@netmarble.com',
//     manager_name: '이삭 [Sack Lee]',
//     name: '2N_TWHKMO_DE 14',
//     phone: '02-2271-6514',
//     query_config: { meta: { idType: ID_TYPE.ADID } },
//     restore_content: null,
//     schedules: [],
//     target_games: ['acasino', 'afive'],
//     created_datetime: '2021-07-01T08:24:35.000Z',
//     modified_datetime: '2021-07-01T08:24:55.000Z'
//   },
//   {
//     create_source: CREATE_SOURCE.CREATE,
//     department_name: '개인화서비스개발팀',
//     description: '2N_대홍마_디타겟팅용 최근 14일 접속유저',
//     id: 613,
//     include_columns: ['id'],
//     mail: 'dltkr77@netmarble.com',
//     manager_name: '이삭 [Sack Lee]',
//     name: '2N_TWHKMO_DE 14',
//     phone: '02-2271-6514',
//     query_config: { meta: { idType: ID_TYPE.ADID } },
//     restore_content: null,
//     schedules: [],
//     target_games: ['acasino', 'afive'],
//     created_datetime: '2021-07-01T08:24:35.000Z',
//     modified_datetime: '2021-07-01T08:24:55.000Z'
//   },
//   {
//     create_source: CREATE_SOURCE.TEMPLATE,
//     department_name: '개인화서비스개발팀',
//     description: '2N_대홍마_디타겟팅용 최근 14일 접속유저',
//     id: 613,
//     include_columns: ['id'],
//     mail: 'dltkr77@netmarble.com',
//     manager_name: '이삭 [Sack Lee]',
//     name: '2N_TWHKMO_DE 14',
//     phone: '02-2271-6514',
//     query_config: { meta: { idType: ID_TYPE.PID } },
//     restore_content: null,
//     schedules: [],
//     target_games: ['acasino', 'afive'],
//     created_datetime: '2021-07-01T08:24:35.000Z',
//     modified_datetime: '2021-07-01T08:24:55.000Z'
//   },
//   {
//     create_source: CREATE_SOURCE.CREATE,
//     department_name: '개인화서비스개발팀',
//     description: '2N_대홍마_디타겟팅용 최근 14일 접속유저',
//     id: 613,
//     include_columns: ['id'],
//     mail: 'dltkr77@netmarble.com',
//     manager_name: '이삭 [Sack Lee]',
//     name: '2N_TWHKMO_DE 14',
//     phone: '02-2271-6514',
//     query_config: { meta: { idType: ID_TYPE.ADID } },
//     restore_content: null,
//     schedules: [],
//     target_games: ['acasino', 'afive'],
//     created_datetime: '2021-07-01T08:24:35.000Z',
//     modified_datetime: '2021-07-01T08:24:55.000Z'
//   },
//   {
//     create_source: CREATE_SOURCE.CREATE,
//     department_name: '개인화서비스개발팀',
//     description: '2N_대홍마_디타겟팅용 최근 14일 접속유저',
//     id: 613,
//     include_columns: ['id'],
//     mail: 'dltkr77@netmarble.com',
//     manager_name: '이삭 [Sack Lee]',
//     name: '2N_TWHKMO_DE 14',
//     phone: '02-2271-6514',
//     query_config: { meta: { idType: ID_TYPE.ADID } },
//     restore_content: null,
//     schedules: [],
//     target_games: ['acasino', 'afive'],
//     created_datetime: '2021-07-01T08:24:35.000Z',
//     modified_datetime: '2021-07-01T08:24:55.000Z'
//   }
// ]
//
// export const mockSegments = (data: ISegmentData[] = mockSegmentData()): ISegment[] =>
//   data.map((item) => new Segment(item))
